language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends libglib2.0-dev libxml2-dev gtk-doc-tools

script:
  - ./autogen.sh
  - make -j2
  - make check
